apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-operator-v1
  annotations:
    packages.thetechnick.ninja/phase: deploy
  labels:
    app.kubernetes.io/name: example-operator
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example-operator
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-operator
        app.kubernetes.io/version: v1
    spec:
      # serviceAccountName: example-operator
      containers:
      - name: manager
        image: quay.io/nschiede/example-operator-manager:main-b24d303
        env:
        - name: KUBECONFIG
          value: /test/kubeconfig
        args:
        # - --enable-leader-election
        - --label-selector=operator-version=v1
        - --version=v1
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
          - mountPath: /test
            name: hosted-cluster-kubeconfig
      volumes:
      - name: hosted-cluster-kubeconfig
        secret:
          secretName: admin-kubeconfig
