apiVersion: packages.thetechnick.ninja/v1alpha1
kind: ObjectDeployment
metadata:
  name: example-operator
  namespace: cluster-01
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-operator
    spec:
      phases:
      - name: namespace
        class: hosted-cluster
      - name: crds-and-rbac
        class: hosted-cluster
      - name: deploy
      - name: handover
        class: hosted-cluster
      readinessProbes:
      - selector:
          type: Kind
          kind:
            group: apiextensions.k8s.io
            kind: CustomResourceDefinition
        probes:
        - type: Condition
          condition:
            type: Established
            status: "True"
      - selector:
          type: Kind
          kind:
            group: apps
            kind: Deployment
        probes:
        - type: Condition
          condition:
            type: Available
            status: "True"
        - type: FieldsEqual
          fieldsEqual:
            fieldA: .status.updatedReplicas
            fieldB: .status.replicas
      - selector:
          type: Kind
          kind:
            group: coordination.thetechnick.ninja
            kind: ClusterHandover
        probes:
        - type: Condition
          condition:
            type: Completed
            status: "True"
