apiVersion: v1
kind: ServiceAccount
metadata:
  name: package-operator
  namespace: package-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: package-loader
  namespace: package-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: package-loader
rules:
- apiGroups:
  - packages.thetechnick.ninja
  resources:
  - packages
  - packages/finalizers
  - clusterpackages
  - clusterpackages/finalizers
  - objectdeployments
  - objectdeployments/finalizers
  - clusterobjectdeployments
  - clusterobjectdeployments/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: package-loader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: package-loader
subjects:
- kind: ServiceAccount
  name: package-loader
  namespace: package-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: package-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: package-operator
  namespace: package-operator-system
