apiVersion: packages.thetechnick.ninja/v1alpha1
kind: PackageDeployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      phases:
      - name: deploy
        objects:
        - object:
            apiVersion: v1
            kind: ConfigMap
            metadata: 
              name: nginx-important
            data: {}
        - object:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: nginx-deployment
              labels:
                app: nginx
              annotations:
                packages.thetechnick.ninja/phase: deploy
            spec:
              replicas: 3
              selector:
                matchLabels:
                  app: nginx
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                  - name: nginx
                    image: nginx:1.14.2
                    ports:
                    - containerPort: 80
      readinessProbes:
      - name: Available
        selector:
          type: Kind
          kind:
            group: apps
            kind: Deployment
        probe:
          type: Condition
          condition:
            type: Available
            status: "True"
      - name: Updated
        selector:
          type: Kind
          kind:
            group: apps
            kind: Deployment
        probe:
          type: FieldsEqual
          fieldsEqual:
            fieldA: .status.updatedReplicas
            fieldB: .status.replicas
