apiVersion: v1
kind: ServiceAccount
metadata:
  name: package-phase-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: package-phase-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - packages.thetechnick.ninja
  resources:
  - objectsetphases
  - objectsetphases/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: package-phase-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: package-phase-operator
subjects:
- kind: ServiceAccount
  name: package-phase-operator
