apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.metadata.name}}
  labels:
    app: {{.metadata.name}}
  annotations:
    packages.thetechnick.ninja/phase: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.metadata.name}}
  template:
    metadata:
      labels:
        app: {{.metadata.name}}
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
