apiVersion: coordination.thetechnick.ninja/v1alpha1
kind: Handover
metadata:
  name: config-maps
spec:
  strategy:
    type: Relabel
    relabel:
      label: operator-version
      oldValue: v1
      newValue: v2
  target:
    group: ""
    kind: ConfigMap
    version: v1
  probes:
  - type: FieldsEqual
    fieldsEqual:
      fieldA: .data.key1
      fieldB: .metadata.annotations.test
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: cm-1
  labels:
    operator-version: v1
data:
  key1: test123
  key2: test123
  key3: test123
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: cm-2
  labels:
    operator-version: v1
data:
  key1: test123
  key2: test123
  key3: test123
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: cm-3
  labels:
    operator-version: v1
data:
  key1: test123
  key2: test123
  key3: test123
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: cm-4
  labels:
    operator-version: v1
data:
  key1: test123
  key2: test123
  key3: test123
